import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import QueryProvider from "@/react-query/query-provider";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-grotesk-regular`}
      >
        <AntdRegistry>
          <QueryProvider>{children}</QueryProvider>
          <Toaster richColors position="top-right" />
        </AntdRegistry>
      </body>
    </html>
  );
}
